{
	'name': 'AARSOL HR Extentsion',
	'version': '13.0.1.0.1',
	'summary': """Customized Feature of Human Resource Module""",
	'description': 'AARSOL HR Extentsion Module',
	'category': 'hr',
	'sequence': 5,
	'author': 'AARSOL',
	'company': 'AARSOL',
	'website': "http://www.aarsol.com/",
	'depends': ['hr','hr_skills','hr_payroll'],
	'data': [
		'security/ir.model.access.csv',
		'reports/payslip_report_ext.xml',
		'views/hr_view.xml',
		'views/hr_salary_inputs_view.xml',
		'views/hr_payslip_view.xml',
		'views/hr_config_view.xml',
		'views/res_config_setting_view.xml',
		'wizard/wps_view.xml',
		'menus/hr_ext_menu.xml',
	],
	'demo': [
	],
	'license': 'AGPL-3',
	'installable': True,
	'auto_install': False,
	'application': True,
}
